-- Q1
-- Count total students in each city.

-- Q2
-- Find average marks city-wise.

-- Q3
-- Find maximum marks in each city.

-- Q4
-- Find minimum marks in each city.

-- Q5
-- Count total enrollments per student.

-- Q6
-- Find total course fees paid by each student.

-- Q7
-- Find average course fees teacher-wise.

-- Q8
-- Count total courses handled by each teacher.

-- Q9
-- Find cities having more than 2 students.

-- Q10
-- Find students with total fees > 10000.

-- Q11
-- Find teachers whose salary > average salary.

-- Q12
-- Find highest revenue generating course.

-- Q13
-- Find total enrollments per course.

-- Q14
-- Find average student marks per teacher.

-- Q15
-- Count male and female students separately.

-- Q16
-- Find duplicate marks students.

-- Q17
-- Find cities where average marks > 80.

-- Q18
-- Find teacher handling maximum students.

-- Q19
-- Find total revenue generated by each teacher.

-- Q20
-- Find students enrolled in exactly 2 courses.

-- Q21
-- Find total enrollments month-wise.

-- Q22
-- Find courses having average student marks > 85.

-- Q23
-- Find students whose total fees are above average fees.

-- Q24
-- Find city contributing maximum revenue.

-- Q25
-- Find teachers whose courses have more than 3 enrollments.


-- Q1
-- Show student names with their course names.

-- Q2
-- Show student names with course fees.

-- Q3
-- Show students enrolled after '2025-02-03'.

-- Q4
-- Show courses taught by teacher 'Matsuzaka'.

-- Q5
-- Show all students with teacher names.

-- Q6
-- Find students enrolled in more than 2 courses.

-- Q7
-- Show total fees paid by each student.

-- Q8
-- Show highest fee course with student name.

-- Q9
-- Show teacher salary with enrolled student names.

-- Q10
-- Find students enrolled in both Math Master and Science Pro.

-- Q11
-- Show courses having more than 2 students.

-- Q12
-- Show city-wise total enrollments.

-- Q13
-- Show teacher handling maximum courses.

-- Q14
-- Find students who enrolled in expensive courses (>7000).

-- Q15
-- Show average course fee per student.

-- Q16
-- Find teachers whose students average marks > 80.

-- Q17
-- Show course count handled by each teacher.

-- Q18
-- Find students not enrolled in any course.

-- Q19
-- Show latest enrollment of every student.

-- Q20
-- Find second highest fee course with student names.

-- Q21
-- Show top 3 students by total course fees.

-- Q22
-- Find common courses between Shinchan and Kazama.

-- Q23
-- Show students enrolled under same teacher multiple times.

-- Q24
-- Find course generating highest revenuee

-- Q25
-- Show student-course-teacher hierarchy.